vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        event:
            uri_prefix: public/images/event
            upload_destination: '%kernel.project_dir%/public/images/event'
            namer:       Vich\UploaderBundle\Naming\SmartUniqueNamer
